### ISSUE TITLE
Disk Peripheral

### ISSUE THREAD

**Issue by pranav12321** [ut-utp/core#187] opened 2022-08-31 16:32 UTC
### what

[[ What is this feature about? ]]

### steps
 - [ ] [[ steps ]]

[[ What steps will we need to take to implement this feature? ]]

### where
branch: `feat-`

[[
This should be:
 - N/A if this feature is not currently being worked on
 - [`feat-<feature-name>`](//github.com/ut-utp/<repo>/tree/feat-feature-name) if this is being worked on in _this repo_
 - [`org/repo#<branch-name>`](//github.com/org/repo/tree/branch-name) if this is being worked on in _another repo_
]]

### open questions

[[
Unknowns and questions about the design/implementation of this feature.
This is kind of a catch all for anything that doesn't fit in the above categories.
]]

**Comment by rrbutani** [comment] 2022-08-31 17:23
I think this is a duplicate of #54

**Comment by rrbutani** [comment] 2022-08-31 18:54
@pranav12321 I'm going to close this in favor of #54; feel free to re-open if this issue is actually about something else.

**Closed as not planned by rrbutani** 2022-08-31 18:54 UTC
Labels: ✨ feature
